gnodeb:
  controlif:
    ip: "192.168.1.187" 
    port: 38412
  dataif:
    ip: "192.168.1.187" 
    port: 2152
  plmnlist:
    mcc: "001"
    mnc: "01"
    tac: "000001"
    gnbid: "000008"
  slicesupportlist:
    sst: "01"
    sd: "010203" # optional, can be removed if not used
ue:
  msin: "0100007487"
  key: "5122250214c33e723a5dd523fc145fc0"
  opc: "981d464c7c52eb6e5036234984ad0bcf"
  amf: "8000"
  sqn: "00000000"
  dnn: "hexa"
  routingindicator: "0000"
  hplmn:
    mcc: "001"
    mnc: "01"
  snssai:
    sst: 01
    sd: "010203" # optional, can be removed if not used
  integrity:
    nia0: false
    nia1: true
    nia2: false
    nia3: false
  ciphering:
    nea0: false
    nea1: false
    nea2: false
    nea3: false
amfif:
  - ip: " "  # AMF External IP 
    port: 38412
logs:
    level: 100
